//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebWorkerExch_WorkerRole.SystemInfoService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemInfoService.ISystemInfo")]
    public interface ISystemInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemInfo/SendSystemInfo", ReplyAction="http://tempuri.org/ISystemInfo/SendSystemInfoResponse")]
        void SendSystemInfo(ProAzureCommon.SystemMessageExchange ds);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISystemInfo/SendSystemInfo", ReplyAction="http://tempuri.org/ISystemInfo/SendSystemInfoResponse")]
        System.IAsyncResult BeginSendSystemInfo(ProAzureCommon.SystemMessageExchange ds, System.AsyncCallback callback, object asyncState);
        
        void EndSendSystemInfo(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemInfoChannel : WebWorkerExch_WorkerRole.SystemInfoService.ISystemInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemInfoClient : System.ServiceModel.ClientBase<WebWorkerExch_WorkerRole.SystemInfoService.ISystemInfo>, WebWorkerExch_WorkerRole.SystemInfoService.ISystemInfo {
        
        private BeginOperationDelegate onBeginSendSystemInfoDelegate;
        
        private EndOperationDelegate onEndSendSystemInfoDelegate;
        
        private System.Threading.SendOrPostCallback onSendSystemInfoCompletedDelegate;
        
        public SystemInfoClient() {
        }
        
        public SystemInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SendSystemInfoCompleted;
        
        public void SendSystemInfo(ProAzureCommon.SystemMessageExchange ds) {
            base.Channel.SendSystemInfo(ds);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginSendSystemInfo(ProAzureCommon.SystemMessageExchange ds, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSendSystemInfo(ds, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public void EndSendSystemInfo(System.IAsyncResult result) {
            base.Channel.EndSendSystemInfo(result);
        }
        
        private System.IAsyncResult OnBeginSendSystemInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            ProAzureCommon.SystemMessageExchange ds = ((ProAzureCommon.SystemMessageExchange)(inValues[0]));
            return this.BeginSendSystemInfo(ds, callback, asyncState);
        }
        
        private object[] OnEndSendSystemInfo(System.IAsyncResult result) {
            this.EndSendSystemInfo(result);
            return null;
        }
        
        private void OnSendSystemInfoCompleted(object state) {
            if ((this.SendSystemInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SendSystemInfoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SendSystemInfoAsync(ProAzureCommon.SystemMessageExchange ds) {
            this.SendSystemInfoAsync(ds, null);
        }
        
        public void SendSystemInfoAsync(ProAzureCommon.SystemMessageExchange ds, object userState) {
            if ((this.onBeginSendSystemInfoDelegate == null)) {
                this.onBeginSendSystemInfoDelegate = new BeginOperationDelegate(this.OnBeginSendSystemInfo);
            }
            if ((this.onEndSendSystemInfoDelegate == null)) {
                this.onEndSendSystemInfoDelegate = new EndOperationDelegate(this.OnEndSendSystemInfo);
            }
            if ((this.onSendSystemInfoCompletedDelegate == null)) {
                this.onSendSystemInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSendSystemInfoCompleted);
            }
            base.InvokeAsync(this.onBeginSendSystemInfoDelegate, new object[] {
                        ds}, this.onEndSendSystemInfoDelegate, this.onSendSystemInfoCompletedDelegate, userState);
        }
    }
}
